--
-- PostgreSQL database dump
--

\restrict SrsH1OM3xWpsL3UJ9mqjhEaUJjHXZkLgXU95VWlkTpUHKFkLXUcHn4i04sq2q7r

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: users; Type: TABLE; Schema: public; Owner: techfix_usr
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(100) NOT NULL,
    full_name character varying(100),
    password character varying(255) NOT NULL,
    role character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    username character varying(50) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['CLIENTE'::character varying, 'TECNICO'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO techfix_usr;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: techfix_usr
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: techfix_usr
--

COPY public.users (id, active, created_at, email, full_name, password, role, updated_at, username) FROM stdin;
\.


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techfix_usr
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- Name: users uk_users_email; Type: CONSTRAINT; Schema: public; Owner: techfix_usr
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_email UNIQUE (email);


--
-- Name: users uk_users_username; Type: CONSTRAINT; Schema: public; Owner: techfix_usr
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_username UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: techfix_usr
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict SrsH1OM3xWpsL3UJ9mqjhEaUJjHXZkLgXU95VWlkTpUHKFkLXUcHn4i04sq2q7r

