--
-- PostgreSQL database dump
--

\restrict CwJKsazNkMqgUpJBKD3AWrfgb8zKbXvElH94GXyhcMDDyk4wUhV9S9hDYolract

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: idempotency_keys; Type: TABLE; Schema: public; Owner: techfix_pay
--

CREATE TABLE public.idempotency_keys (
    idempotency_key character varying(36) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    pago_id bigint,
    response_body text NOT NULL,
    status_code integer NOT NULL
);


ALTER TABLE public.idempotency_keys OWNER TO techfix_pay;

--
-- Name: pago; Type: TABLE; Schema: public; Owner: techfix_pay
--

CREATE TABLE public.pago (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    descripcion character varying(255),
    estado_pago character varying(20) NOT NULL,
    fecha_pago date NOT NULL,
    id_visita_tecnica bigint NOT NULL,
    metodo_pago character varying(20) NOT NULL,
    monto numeric(10,2) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT pago_estado_pago_check CHECK (((estado_pago)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'PAGADO'::character varying, 'ANULADO'::character varying])::text[]))),
    CONSTRAINT pago_metodo_pago_check CHECK (((metodo_pago)::text = ANY ((ARRAY['EFECTIVO'::character varying, 'TARJETA_DEBITO'::character varying, 'TARJETA_CREDITO'::character varying, 'TRANSFERENCIA'::character varying])::text[])))
);


ALTER TABLE public.pago OWNER TO techfix_pay;

--
-- Name: pago_id_seq; Type: SEQUENCE; Schema: public; Owner: techfix_pay
--

ALTER TABLE public.pago ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pago_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: idempotency_keys; Type: TABLE DATA; Schema: public; Owner: techfix_pay
--

COPY public.idempotency_keys (idempotency_key, created_at, pago_id, response_body, status_code) FROM stdin;
\.


--
-- Data for Name: pago; Type: TABLE DATA; Schema: public; Owner: techfix_pay
--

COPY public.pago (id, created_at, descripcion, estado_pago, fecha_pago, id_visita_tecnica, metodo_pago, monto, updated_at) FROM stdin;
\.


--
-- Name: pago_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techfix_pay
--

SELECT pg_catalog.setval('public.pago_id_seq', 1, false);


--
-- Name: idempotency_keys idempotency_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: techfix_pay
--

ALTER TABLE ONLY public.idempotency_keys
    ADD CONSTRAINT idempotency_keys_pkey PRIMARY KEY (idempotency_key);


--
-- Name: pago pago_pkey; Type: CONSTRAINT; Schema: public; Owner: techfix_pay
--

ALTER TABLE ONLY public.pago
    ADD CONSTRAINT pago_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict CwJKsazNkMqgUpJBKD3AWrfgb8zKbXvElH94GXyhcMDDyk4wUhV9S9hDYolract

