spring:
  application:
    name: techfix-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]
            allowedHeaders: "*"
      routes:
        - id: users-login
          uri: "http://svc_roles:8080"
          predicates:
            - Path=/gateway/users/login
            - Method=POST
          filters:
            - RewritePath=/gateway/users/login, /api/v1/users/login
        - id: users-register
          uri: "http://svc_roles:8080"
          predicates:
            - Path=/gateway/users/register
            - Method=POST
          filters:
            - RewritePath=/gateway/users/register, /api/v1/users/register
        - id: users-create
          uri: "http://svc_roles:8080"
          predicates:
            - Path=/gateway/users
            - Method=POST
          filters:
            - RewritePath=/gateway/users, /api/v1/users
        - id: users-protected
          uri: "http://svc_roles:8080"
          predicates:
            - Path=/gateway/users/**
          filters:
            - RewritePath=/gateway/users(?<seg>/?.*), /api/v1/users\${seg}
        - id: pagos
          uri: "http://svc_pagos:8081"
          predicates:
            - Path=/gateway/pagos/**
          filters:
            - RewritePath=/gateway/pagos(?<seg>/?.*), /pago\${seg}
        - id: stock
          uri: "http://svc_stock:8082"
          predicates:
            - Path=/gateway/stock/**
          filters:
            - RewritePath=/gateway/stock(?<seg>/?.*), /api/v1/products\${seg}
        - id: stock-categories
          uri: "http://svc_stock:8082"
          predicates:
            - Path=/gateway/categories/**
          filters:
            - RewritePath=/gateway/categories(?<seg>/?.*), /api/v1/categories\${seg}
        - id: citas
          uri: "http://svc_agenda:8083"
          predicates:
            - Path=/gateway/citas/**
          filters:
            - RewritePath=/gateway/citas(?<seg>/?.*), /api/v1/citas\${seg}
        - id: clientes
          uri: "http://svc_agenda:8083"
          predicates:
            - Path=/gateway/clientes/**
          filters:
            - RewritePath=/gateway/clientes(?<seg>/?.*), /api/v1/clientes\${seg}
        - id: tecnicos
          uri: "http://svc_agenda:8083"
          predicates:
            - Path=/gateway/tecnicos/**
          filters:
            - RewritePath=/gateway/tecnicos(?<seg>/?.*), /api/v1/tecnicos\${seg}
server:
  port: ${SERVER_PORT:8090}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.techfix.gateway: DEBUG